variables:
  MSBUILD_PATH: 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe'
  ARTIFACTS_PATH: 'Document Management'
  API_PATH: 'DocumentManagement.Api\bin\Release\Publish'
  LAUNCHER_PATH: 'DocumentManagement.Launcher\bin\Release\net5.0-windows'

stages:
  - build

build_job:
  stage: build
  only:
    - branches
  script:
    - 'nuget restore'
    - '"%MSBUILD_PATH%" /property:Configuration=Release'
    - '"%MSBUILD_PATH%" /t:Restore;Rebuild;Publish /p:SelfContained=True /p:PublishProtocol=FileSystem /p:Configuration=Release /p:PublishDir=bin\Release\Publish /p:RuntimeIdentifier=win-x64'
    - mkdir "%ARTIFACTS_PATH%
    - xcopy /E "%API_PATH%" "%ARTIFACTS_PATH%"
    - mkdir "%ARTIFACTS_PATH%\Launcher"
    - xcopy /E "%LAUNCHER_PATH%" "%ARTIFACTS_PATH%\Launcher"
  artifacts:
    expire_in: 2 days
    paths:
      - '%ARTIFACTS_PATH%'
