variables:
  MSBUILD_PATH: 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe'
  ARTIFACTS_PATH: 'Document Management'
  API_PATH: 'Brio.Docs.Api\bin\Release\Publish'
  LAUNCHER_PATH: 'Brio.Docs.Launcher\bin\Release\net5.0-windows'

stages:
  - build
  - deploy

build:
  stage: build
  only:
    - branches
  script:
    - 'nuget restore'
    - mkdir "%ARTIFACTS_PATH%
    - mkdir "%ARTIFACTS_PATH%\Launcher"
    - '"%MSBUILD_PATH%" /property:Configuration=Release'
    - xcopy /E "%LAUNCHER_PATH%" "%ARTIFACTS_PATH%\Launcher"
    - '"%MSBUILD_PATH%" /t:Restore;Rebuild;Publish /p:SelfContained=True /p:PublishProtocol=FileSystem /p:Configuration=Release /p:PublishDir=bin\Release\Publish /p:RuntimeIdentifier=win-x64 /p:AllowedReferenceRelatedFileExtensions=*.pdb /p:DebugSymbols=false /p:DebugType=none'
    - xcopy /E "%API_PATH%" "%ARTIFACTS_PATH%"
    - copy CHANGELOG.md "%ARTIFACTS_PATH%\CHANGELOG.md"
    - del /S "%ARTIFACTS_PATH%\*.pdb"
  artifacts:
    expire_in: 2 days
    paths:
      - '%ARTIFACTS_PATH%'

tag:
  stage: deploy
  tags:
    - bash
    - docker
  image: ubuntu
  before_script:
    - DEBIAN_FRONTEND=noninteractive apt-get update
    - DEBIAN_FRONTEND=noninteractive apt-get -y install php php-json git git-lfs openssh-client curl
    - DAY_OF_MONTH=$(date +%-d)
    - WEEK_TAG=""
    - if [ $CI_COMMIT_REF_NAME == "development" ] && [ $CI_PIPELINE_SOURCE == "schedule" ]; then WEEK_TAG="w$((DAY_OF_MONTH / 7 + 1))"; fi
  script:
    - VERSION="${BUILD_VERSION_COMMON}${WEEK_TAG}"
    - git config --global user.email "$GIT_EMAIL"
    - git config --global user.name "$GIT_NAME"
    - git remote add $CI_PIPELINE_ID http://oauth2:${GIT_TOKEN}@gitlab.briogroup.ru/mrs/unity/mrs
    - git tag -a $VERSION -m "Version $VERSION"
    - git push $CI_PIPELINE_ID $VERSION
