variables:
  MSBUILD_PATH: 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe'
  API_PATH: '\'

stages:
  - build

build_job:
  stage: build
  only:
    - branches
  script:
    - 'nuget restore'
    - '"%MSBUILD_PATH%" /t:Restore;Rebuild;Publish /p:SelfContained=True /p:PublishProtocol=FileSystem /p:Configuration=Release /p:PublishDir=bin\Release\Publish /p:RuntimeIdentifier=win-x64'
  artifacts:
    expire_in: 2 days
    paths:
      - '%API_PATH%\*'
