//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Brio.Docs.Connections.LementPro.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Brio.Docs.Connections.LementPro.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на /Services/Authentication/Login.do.
        /// </summary>
        internal static string MethodAuthenticationLogin {
            get {
                return ResourceManager.GetString("MethodAuthenticationLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на /Services/Bim/GetChildObjectsByAttribute.do.
        /// </summary>
        internal static string MethodBimChildrenByAttribute {
            get {
                return ResourceManager.GetString("MethodBimChildrenByAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на /Services/Bim/GetListViewObjectAttributes.do.
        /// </summary>
        internal static string MethodBimGetListViewObjectAttributes {
            get {
                return ResourceManager.GetString("MethodBimGetListViewObjectAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на /Services/Category/GetMenuCategories.do.
        /// </summary>
        internal static string MethodCategoriesGetMenuList {
            get {
                return ResourceManager.GetString("MethodCategoriesGetMenuList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на /Services/Files/DocumentFile/GetFile.do.
        /// </summary>
        internal static string MethodFileDownload {
            get {
                return ResourceManager.GetString("MethodFileDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на /Services/Folders/{0}Folder/GetTree.do.
        /// </summary>
        internal static string MethodFolderGetListForCategory {
            get {
                return ResourceManager.GetString("MethodFolderGetListForCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на /Services/{0}/GetList.do.
        /// </summary>
        internal static string MethodGetObjectsList {
            get {
                return ResourceManager.GetString("MethodGetObjectsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на /Services/ObjectBase/Archive.do.
        /// </summary>
        internal static string MethodObjectArchive {
            get {
                return ResourceManager.GetString("MethodObjectArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на /Services/ObjectBase/Create.do.
        /// </summary>
        internal static string MethodObjectCreate {
            get {
                return ResourceManager.GetString("MethodObjectCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на /Services/ObjectBase/Delete.do.
        /// </summary>
        internal static string MethodObjectDelete {
            get {
                return ResourceManager.GetString("MethodObjectDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на /Services/ObjectBase/Edit.do.
        /// </summary>
        internal static string MethodObjectEdit {
            get {
                return ResourceManager.GetString("MethodObjectEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на /Services/ObjectsBase/File/Add.do.
        /// </summary>
        internal static string MethodObjectFileAdd {
            get {
                return ResourceManager.GetString("MethodObjectFileAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на /Services/ObjectsBase/File/BeginUpload.do.
        /// </summary>
        internal static string MethodObjectFileBeginUpload {
            get {
                return ResourceManager.GetString("MethodObjectFileBeginUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на /Services/ObjectsBase/File/EndUpload.do.
        /// </summary>
        internal static string MethodObjectFileEndUpload {
            get {
                return ResourceManager.GetString("MethodObjectFileEndUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на /Services/ObjectsBase/File/UploadPart.do.
        /// </summary>
        internal static string MethodObjectFileUploadPart {
            get {
                return ResourceManager.GetString("MethodObjectFileUploadPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на /Services/ObjectBase/Get.do.
        /// </summary>
        internal static string MethodObjectGet {
            get {
                return ResourceManager.GetString("MethodObjectGet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на /Services/ObjectsBase/Template/GetDefaultTemplate.do.
        /// </summary>
        internal static string MethodObjectGetDefaultTemplate {
            get {
                return ResourceManager.GetString("MethodObjectGetDefaultTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на /Services/Task/Edit.do.
        /// </summary>
        internal static string MethodTaskUpdate {
            get {
                return ResourceManager.GetString("MethodTaskUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на /Services/ObjectTypes/ObjectTypeAttributeDef/GetList.do.
        /// </summary>
        internal static string MethodTypesGetAttributesDefinition {
            get {
                return ResourceManager.GetString("MethodTypesGetAttributesDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на /Services/ObjectTypes/ObjectType/GetTree.do.
        /// </summary>
        internal static string MethodTypesGetTree {
            get {
                return ResourceManager.GetString("MethodTypesGetTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на /Bim.
        /// </summary>
        internal static string UrlCategoryBim {
            get {
                return ResourceManager.GetString("UrlCategoryBim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на /Dictionaries.
        /// </summary>
        internal static string UrlCategoryDictionaries {
            get {
                return ResourceManager.GetString("UrlCategoryDictionaries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на /Documents.
        /// </summary>
        internal static string UrlCategoryDocuments {
            get {
                return ResourceManager.GetString("UrlCategoryDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на /Goals.
        /// </summary>
        internal static string UrlCategoryGoals {
            get {
                return ResourceManager.GetString("UrlCategoryGoals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на /Projects.
        /// </summary>
        internal static string UrlCategoryProjects {
            get {
                return ResourceManager.GetString("UrlCategoryProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на /Tasks.
        /// </summary>
        internal static string UrlCategoryTasks {
            get {
                return ResourceManager.GetString("UrlCategoryTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на /Categories/Defects.
        /// </summary>
        internal static string UrlCustomCategoryDefects {
            get {
                return ResourceManager.GetString("UrlCustomCategoryDefects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на https://briogroup.lement.pro.
        /// </summary>
        internal static string UrlServer {
            get {
                return ResourceManager.GetString("UrlServer", resourceCulture);
            }
        }
    }
}
