//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocumentManagement.Connection.BIM360.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DocumentManagement.Connection.BIM360.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на https://autodesk.com/.
        /// </summary>
        internal static string AutodeskUrl {
            get {
                return ResourceManager.GetString("AutodeskUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на https://developer.api.autodesk.com.
        /// </summary>
        internal static string ForgeUrl {
            get {
                return ResourceManager.GetString("ForgeUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на /project/v1/hubs/{0}.
        /// </summary>
        internal static string GetHubsInfoByIdMethod {
            get {
                return ResourceManager.GetString("GetHubsInfoByIdMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на /project/v1/hubs.
        /// </summary>
        internal static string GetHubsMethod {
            get {
                return ResourceManager.GetString("GetHubsMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на /issues/v1/containers/{0}/quality-issues?&amp;page[limit]={1}&amp;page[offset]={2}.
        /// </summary>
        internal static string GetIssuesMethod {
            get {
                return ResourceManager.GetString("GetIssuesMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на /issues/v1/containers/{0}/ng-issue-types.
        /// </summary>
        internal static string GetNGIssueTypesMethod {
            get {
                return ResourceManager.GetString("GetNGIssueTypesMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на /project/v1/hubs/{0}/projects/{1}.
        /// </summary>
        internal static string GetProjectOfHubMethod {
            get {
                return ResourceManager.GetString("GetProjectOfHubMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на /data/v1/projects/{0}/downloads/{1}.
        /// </summary>
        internal static string GetProjectsDownloadInfoMethod {
            get {
                return ResourceManager.GetString("GetProjectsDownloadInfoMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на /data/v1/projects/{0}/folders/{1}/contents?filter[type]={2}.
        /// </summary>
        internal static string GetProjectsFoldersContentsMethod {
            get {
                return ResourceManager.GetString("GetProjectsFoldersContentsMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на /data/v1/projects/{0}/folders/{1}/search?.
        /// </summary>
        internal static string GetProjectsFoldersSearchMethod {
            get {
                return ResourceManager.GetString("GetProjectsFoldersSearchMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на /project/v1/hubs/{0}/projects/{1}/hub.
        /// </summary>
        internal static string GetProjectsHubMethod {
            get {
                return ResourceManager.GetString("GetProjectsHubMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на /project/v1/hubs/{0}/projects.
        /// </summary>
        internal static string GetProjectsOfHubMethod {
            get {
                return ResourceManager.GetString("GetProjectsOfHubMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на /project/v1/hubs/{0}/projects/{1}/topFolders.
        /// </summary>
        internal static string GetTopFoldersMethod {
            get {
                return ResourceManager.GetString("GetTopFoldersMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на /issues/v1/containers/{0}/quality-issues/{1}.
        /// </summary>
        internal static string PatchIssuesMethod {
            get {
                return ResourceManager.GetString("PatchIssuesMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на authentication/v1/gettoken.
        /// </summary>
        internal static string PostGetTokenMethod {
            get {
                return ResourceManager.GetString("PostGetTokenMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на /issues/v1/containers/{0}/attachments.
        /// </summary>
        internal static string PostIssuesAttachmentsMethod {
            get {
                return ResourceManager.GetString("PostIssuesAttachmentsMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на /issues/v1/containers/{0}/quality-issues.
        /// </summary>
        internal static string PostIssuesMethod {
            get {
                return ResourceManager.GetString("PostIssuesMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на /data/v1/projects/{0}/items.
        /// </summary>
        internal static string PostProjectsItemsMethod {
            get {
                return ResourceManager.GetString("PostProjectsItemsMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на data/v1/projects/{0}/storage.
        /// </summary>
        internal static string PostProjectStorageMethod {
            get {
                return ResourceManager.GetString("PostProjectStorageMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на /data/v1/projects/{0}/versions.
        /// </summary>
        internal static string PostProjectsVersionMethod {
            get {
                return ResourceManager.GetString("PostProjectsVersionMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на /authentication/v1/refreshtoken.
        /// </summary>
        internal static string PostRefreshTokenMethod {
            get {
                return ResourceManager.GetString("PostRefreshTokenMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на /authentication/v1/refreshtoken?response_type=code&amp;client_id={0}&amp;redirect_uri={1}&amp;scope={2}.
        /// </summary>
        internal static string PostRegreshTokenFilteredMethod {
            get {
                return ResourceManager.GetString("PostRegreshTokenFilteredMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на /oss/v2/buckets/{0}/objects/{1}.
        /// </summary>
        internal static string PutBucketsObjectsMethod {
            get {
                return ResourceManager.GetString("PutBucketsObjectsMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на /oss/v2/buckets/{0}/objects/{1}/resumable.
        /// </summary>
        internal static string PutBucketsObjectsResumableMethod {
            get {
                return ResourceManager.GetString("PutBucketsObjectsResumableMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///    &lt;body&gt;You can now close this window!&lt;/body&gt;
        ///&lt;/html&gt;.
        /// </summary>
        internal static string SuccessfulAuthentication {
            get {
                return ResourceManager.GetString("SuccessfulAuthentication", resourceCulture);
            }
        }
    }
}
