//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MRS.DocumentManagement.Connection.Bim360.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MRS.DocumentManagement.Connection.Bim360.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на /oss/v2/buckets/{0}/objects/{1}.
        /// </summary>
        internal static string DeleteBucketsObjectMethod {
            get {
                return ResourceManager.GetString("DeleteBucketsObjectMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на /authentication/v1/authorize?response_type=code&amp;client_id={0}&amp;redirect_uri={1}&amp;scope={2}.
        /// </summary>
        internal static string GetAuthorizeMethod {
            get {
                return ResourceManager.GetString("GetAuthorizeMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на /oss/v2/buckets/{0}/details.
        /// </summary>
        internal static string GetBucketDetailsMethod {
            get {
                return ResourceManager.GetString("GetBucketDetailsMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на /oss/v2/buckets.
        /// </summary>
        internal static string GetBucketsMethod {
            get {
                return ResourceManager.GetString("GetBucketsMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на /oss/v2/buckets/{0}/objects/{1}.
        /// </summary>
        internal static string GetBucketsObjectMethod {
            get {
                return ResourceManager.GetString("GetBucketsObjectMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на /bim360/docs/v1/projects/{0}/folders/{1}/permissions.
        /// </summary>
        internal static string GetCheckFolderPermissionsMethod {
            get {
                return ResourceManager.GetString("GetCheckFolderPermissionsMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на /project/v1/hubs/{0}.
        /// </summary>
        internal static string GetHubsInfoByIdMethod {
            get {
                return ResourceManager.GetString("GetHubsInfoByIdMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на /project/v1/hubs.
        /// </summary>
        internal static string GetHubsMethod {
            get {
                return ResourceManager.GetString("GetHubsMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на /issues/v1/containers/{0}/quality-issues/{1}.
        /// </summary>
        internal static string GetIssueMethod {
            get {
                return ResourceManager.GetString("GetIssueMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на /issues/v1/containers/{0}/quality-issues/{1}/attachments.
        /// </summary>
        internal static string GetIssuesAttachmentMethod {
            get {
                return ResourceManager.GetString("GetIssuesAttachmentMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на /issues/v1/containers/{0}/quality-issues/{1}/comments.
        /// </summary>
        internal static string GetIssuesCommentsMethod {
            get {
                return ResourceManager.GetString("GetIssuesCommentsMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на /issues/v1/containers/{0}/quality-issues.
        /// </summary>
        internal static string GetIssuesMethod {
            get {
                return ResourceManager.GetString("GetIssuesMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на /issues/v1/containers/{0}/ng-issue-types?include=subtypes.
        /// </summary>
        internal static string GetNGIssueTypesMethod {
            get {
                return ResourceManager.GetString("GetNGIssueTypesMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на /project/v1/hubs/{0}/projects/{1}.
        /// </summary>
        internal static string GetProjectOfHubMethod {
            get {
                return ResourceManager.GetString("GetProjectOfHubMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на /hq/v1/regions/eu/accounts/{0}/projects/{1}/companies.
        /// </summary>
        internal static string GetProjectsCompaniesMethodEmea {
            get {
                return ResourceManager.GetString("GetProjectsCompaniesMethodEmea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на /hq/v1/accounts/{0}/projects/{1}/companies.
        /// </summary>
        internal static string GetProjectsCompaniesMethodUS {
            get {
                return ResourceManager.GetString("GetProjectsCompaniesMethodUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на /data/v1/projects/{0}/downloads/{1}.
        /// </summary>
        internal static string GetProjectsDownloadInfoMethod {
            get {
                return ResourceManager.GetString("GetProjectsDownloadInfoMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на /data/v1/projects/{0}/folders/{1}/contents.
        /// </summary>
        internal static string GetProjectsFoldersContentsMethod {
            get {
                return ResourceManager.GetString("GetProjectsFoldersContentsMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на /data/v1/projects/{0}/folders/{1}/search.
        /// </summary>
        internal static string GetProjectsFoldersSearchMethod {
            get {
                return ResourceManager.GetString("GetProjectsFoldersSearchMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на /project/v1/hubs/{0}/projects/{1}/hub.
        /// </summary>
        internal static string GetProjectsHubMethod {
            get {
                return ResourceManager.GetString("GetProjectsHubMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на /hq/v2/regions/eu/accounts/{0}/projects/{1}/industry_roles.
        /// </summary>
        internal static string GetProjectsIndustryRolesMethodEmea {
            get {
                return ResourceManager.GetString("GetProjectsIndustryRolesMethodEmea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на /hq/v2/accounts/{0}/projects/{1}/industry_roles.
        /// </summary>
        internal static string GetProjectsIndustryRolesMethodUS {
            get {
                return ResourceManager.GetString("GetProjectsIndustryRolesMethodUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на /data/v1/projects/{0}/items/{1}.
        /// </summary>
        internal static string GetProjectsItemMethod {
            get {
                return ResourceManager.GetString("GetProjectsItemMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на /data/v1/projects/{0}/items/{1}/versions.
        /// </summary>
        internal static string GetProjectsItemsVersionsMethod {
            get {
                return ResourceManager.GetString("GetProjectsItemsVersionsMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на /project/v1/hubs/{0}/projects.
        /// </summary>
        internal static string GetProjectsOfHubMethod {
            get {
                return ResourceManager.GetString("GetProjectsOfHubMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на /bim360/admin/v1/projects/{0}/users.
        /// </summary>
        internal static string GetProjectsUsersMethod {
            get {
                return ResourceManager.GetString("GetProjectsUsersMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на /issues/v1/containers/{0}/root-causes.
        /// </summary>
        internal static string GetRootCausesMethod {
            get {
                return ResourceManager.GetString("GetRootCausesMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на /project/v1/hubs/{0}/projects/{1}/topFolders.
        /// </summary>
        internal static string GetTopFoldersMethod {
            get {
                return ResourceManager.GetString("GetTopFoldersMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на /hq/v1/accounts/{0}/users/{1}.
        /// </summary>
        internal static string GetUserMethodEmea {
            get {
                return ResourceManager.GetString("GetUserMethodEmea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на /hq/v1/regions/eu/accounts/{0}/users/{1}.
        /// </summary>
        internal static string GetUserMethodUS {
            get {
                return ResourceManager.GetString("GetUserMethodUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на /userprofile/v1/users/@me.
        /// </summary>
        internal static string GetUsersAtMeMethod {
            get {
                return ResourceManager.GetString("GetUsersAtMeMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на /issues/v1/containers/{0}/users/me.
        /// </summary>
        internal static string GetUsersMeMethod {
            get {
                return ResourceManager.GetString("GetUsersMeMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на /hq/v1/regions/eu/accounts/{0}/users.
        /// </summary>
        internal static string GetUsersMethodEmea {
            get {
                return ResourceManager.GetString("GetUsersMethodEmea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на /hq/v1/accounts/{0}/users.
        /// </summary>
        internal static string GetUsersMethodUS {
            get {
                return ResourceManager.GetString("GetUsersMethodUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .mrs.
        /// </summary>
        internal static string MrsFileName {
            get {
                return ResourceManager.GetString("MrsFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на /issues/v1/containers/{0}/quality-issues/{1}.
        /// </summary>
        internal static string PatchIssuesMethod {
            get {
                return ResourceManager.GetString("PatchIssuesMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на /authentication/v1/authenticate.
        /// </summary>
        internal static string PostAuthenticateMethod {
            get {
                return ResourceManager.GetString("PostAuthenticateMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на /oss/v2/buckets.
        /// </summary>
        internal static string PostBucketsMethod {
            get {
                return ResourceManager.GetString("PostBucketsMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на /authentication/v1/gettoken.
        /// </summary>
        internal static string PostGetTokenMethod {
            get {
                return ResourceManager.GetString("PostGetTokenMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на /issues/v1/containers/{0}/attachments.
        /// </summary>
        internal static string PostIssuesAttachmentsMethod {
            get {
                return ResourceManager.GetString("PostIssuesAttachmentsMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на /issues/v1/containers/{0}/quality-issues.
        /// </summary>
        internal static string PostIssuesMethod {
            get {
                return ResourceManager.GetString("PostIssuesMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на /data/v1/projects/{0}/items.
        /// </summary>
        internal static string PostProjectsItemsMethod {
            get {
                return ResourceManager.GetString("PostProjectsItemsMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на /data/v1/projects/{0}/storage.
        /// </summary>
        internal static string PostProjectStorageMethod {
            get {
                return ResourceManager.GetString("PostProjectStorageMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на /data/v1/projects/{0}/versions.
        /// </summary>
        internal static string PostProjectsVersionMethod {
            get {
                return ResourceManager.GetString("PostProjectsVersionMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на /authentication/v1/refreshtoken.
        /// </summary>
        internal static string PostRefreshTokenMethod {
            get {
                return ResourceManager.GetString("PostRefreshTokenMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на /oss/v2/buckets/{0}/objects/{1}.
        /// </summary>
        internal static string PutBucketsObjectsMethod {
            get {
                return ResourceManager.GetString("PutBucketsObjectsMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на /oss/v2/buckets/{0}/objects/{1}/resumable.
        /// </summary>
        internal static string PutBucketsObjectsResumableMethod {
            get {
                return ResourceManager.GetString("PutBucketsObjectsResumableMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///    &lt;body&gt;You can now close this window!&lt;/body&gt;
        ///&lt;/html&gt;.
        /// </summary>
        internal static string SuccessfulAuthentication {
            get {
                return ResourceManager.GetString("SuccessfulAuthentication", resourceCulture);
            }
        }
    }
}
