//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MRS.DocumentManagement.Launcher.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MRS.DocumentManagement.Launcher.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Документооборот запущен.
        /// </summary>
        public static string Label_DMStarted {
            get {
                return ResourceManager.GetString("Label_DMStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Документооборот остановлен.
        /// </summary>
        public static string Label_DMStopped {
            get {
                return ResourceManager.GetString("Label_DMStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выход.
        /// </summary>
        public static string Label_Exit {
            get {
                return ResourceManager.GetString("Label_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cкрыть консоль.
        /// </summary>
        public static string Label_HideConsole {
            get {
                return ResourceManager.GetString("Label_HideConsole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Показать консоль.
        /// </summary>
        public static string Label_ShowConsole {
            get {
                return ResourceManager.GetString("Label_ShowConsole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Открыть файл настроек.
        /// </summary>
        public static string Label_ShowSettings {
            get {
                return ResourceManager.GetString("Label_ShowSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Открыть Swagger.
        /// </summary>
        public static string Label_ShowSwagger {
            get {
                return ResourceManager.GetString("Label_ShowSwagger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Запустить документооборот.
        /// </summary>
        public static string Label_StartDM {
            get {
                return ResourceManager.GetString("Label_StartDM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Необходимо указать путь к &apos;DocumentManagement.Api.exe&apos;!.
        /// </summary>
        public static string Message_Path_not_found {
            get {
                return ResourceManager.GetString("Message_Path_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Файл не найден!\n{0}.
        /// </summary>
        public static string MessageFormat_File_not_found {
            get {
                return ResourceManager.GetString("MessageFormat_File_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Документооборот BRIO MRS.
        /// </summary>
        public static string Tooltip_Dm_Brio_Mrs {
            get {
                return ResourceManager.GetString("Tooltip_Dm_Brio_Mrs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Остановить документооборот и закрыть приложение.
        /// </summary>
        public static string Tooltip_StopDmAndExit {
            get {
                return ResourceManager.GetString("Tooltip_StopDmAndExit", resourceCulture);
            }
        }
    }
}
